add HW27
AleksandrPitelin/Python_HW pull request #15
Opened 2023-03-17 11:50 UTC by AleksandrPitelin

add HW27

2023-03-18 19:02 UTC, klymenok requested changes

2023-03-18 19:02 UTC, klymenok commented on HomeWork_27/HW27.html
> +<!--// btn=document.createElement('BUTTON');-->
Видаліть цей коментар, якщо вам не потрібен цей код

2023-03-24 21:30 UTC, klymenok commented on HomeWork_27/document.js
> +let i=0;
@AleksandrPitelin коментар не враховано

2023-03-24 21:30 UTC, klymenok commented on HomeWork_27/HW27.html
> +<!--// btn=document.createElement('BUTTON');-->
@AleksandrPitelin коментар не враховано

2023-03-24 21:30 UTC, klymenok requested changes
Не враховані попередні коментарі

2023-03-25 09:53 UTC, AleksandrPitelin commented
> 

забыл новые файлы запушить

2023-03-25 20:29 UTC, klymenok approved these changes
Looks good!

2023-03-30 16:18 UTC, merged