Home work 14
AleksandrPitelin/Python_HW pull request #9
Opened 2023-02-01 11:19 UTC by AleksandrPitelin

HomeWork_14/HW14.py

2023-02-19 15:21 UTC, AleksandrPitelin commented on HomeWork_14/HW14.py
> +        tel = re.search(r"(\+?3?8?0)(\d+)", p)
отдельно работает, а в коде не хочет

2023-02-28 20:17 UTC, klymenok requested changes

2023-02-28 20:17 UTC, klymenok commented on HomeWork_14/HW14.py
> +    with open('/Json_hw14', 'r') as file:
`/` at the beginning of the filename tells that it is an absolute path. It means that the file will be created in the root of a filesystem which is not good. Remove that slash ('/')

2023-02-28 20:17 UTC, klymenok commented on HomeWork_14/HW14.py
> +            with open("/Json_hw14", 'w+') as file_json:
`/` at the beginning of the filename tells that it is an absolute path. It means, that the file will be created in the root of a filesystem which is not good. Remove that slash ('/')

2023-02-28 20:17 UTC, klymenok commented on HomeWork_14/HW14.py
> +        tel = re.search(r"^(\\+380|380|0)[0-9]{9}$", p)
It doesn't work because of `\\+`. Change it to `\+` and it will be correct

2023-03-03 21:02 UTC, klymenok approved these changes
Looks good!

2023-03-16 11:55 UTC, merged